name: Template

on:
  push:
    branches:
      - main

jobs:
  trigger_ci_template:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI Template
        uses: owner/ci-template-repo@main
        with:
          event-type: trigger-ci
          service-name: bolerplatename
